zookeeper:
  downloadurl: <Add downloadurl>
  user: zookeeper
  group: zookeeper
  install: /install
  config_file: /install/zookeeper/conf/zoo.cfg
  service_name: zookeeper
  systemd_file: /etc/systemd/system
  config:
    maxClientCnxns: 0
    initLimit: 10
    syncLimit: 5
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    clientPort: 2181
    dataDir: /var/lib/zookeeper
  environment:
    #KAFKA_HEAP_OPTS: "-Xmx1000M"
  systemd:
    enabled: yes
    state: started
