- name: Create a ext4 filesystem on /dev/sdb
  filesystem:
    fstype: ext4
    dev: /dev/sdb

- name: Create directory /install
  file:
    path: /install
    state: directory

- name: Mount install read-write
  mount:
    path: /install
    opts: rw
    state: mounted
    src: /dev/sdb
    fstype: ext4
